# This is a basic workflow to help you get started with Actions

name: UNIT_TESTS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ mbed-os-5.15 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          # sudo apt-get update -y
          git clone https://github.com/ARMmbed/mbed-os.git
          cd mbed-os
          git checkout mbed-os-5.15
          # sudo apt-get install -y python3-setuptools
          # sudo apt-get install gcc libpq-dev -y
          # sudo apt-get install python-dev  python-pip -y
          # sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
          # pip3 install wheel
          # pip install wheel
          # pip install mbed-cli
          # mbed --help
          ls
